name: Publish release
on:
  release:
    types: [created]
jobs:
  release-js:
    name: 'jsbt v0.4.0-pre' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/release.yml@fb1b826bd8f609dacb350852b4bc5038b9b86231
    with:
      build-path: test/build
    secrets:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    permissions:
      contents: write
      id-token: write
      attestations: write
