name: Publish release
on:
  release:
    types: [created]
jobs:
  release-js:
    name: 'jsbt v0.4.0' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/release.yml@3b4712c94bff7a5da5c968f783292061e81b218c
    with:
      build-path: test/build
      # slow-types: false
    secrets:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    permissions:
      contents: write
      id-token: write
      attestations: write
