name: Run JS tests
on:
  push:
jobs:
  node:
    name: Node v${{ matrix.node }}
    runs-on: ubuntu-24.04-arm
    env:
      MSHOULD_FAST: 1
    strategy:
      matrix: # LTS on Jan 2025. Hardcoded is more secure
        node: [20, 22]
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
        with:
          submodules: ${{ inputs.submodules || false }}
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          registry-url: "https://registry.npmjs.org"
          cache: npm
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
  bun:
    name: Bun
    runs-on: ubuntu-24.04-arm
    env:
      MSHOULD_FAST: 1
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
        with:
          submodules: ${{ inputs.submodules || false }}
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run --if-present build
      - run: bun run --if-present test:bun
        name: Run test:bun if present
  deno:
    name: Deno
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
        with:
          submodules: ${{ inputs.submodules || false }}
      - uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2
        with:
          deno-version: v2.x
      - run: grep -q 'test:deno' package.json && deno install || exit 0
        name: Run deno install if test:deno is present
      - run: grep -q 'build' package.json && deno task build || exit 0
        name: Run build if present
      - run: grep -q 'test:deno' package.json && deno task test:deno || exit 0
        name: Run test:deno if present
  lint:
    name: Lint
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          registry-url: "https://registry.npmjs.org"
          cache: npm
      - run: npm install
      - run: npm run build --if-present
      - run: npm run lint --if-present
  coverage:
    name: Measure coverage
    runs-on: ubuntu-24.04-arm
    env:
      MSHOULD_FAST: 0
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
        with:
          submodules: ${{ inputs.submodules || false }}
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          registry-url: "https://registry.npmjs.org"
          cache: npm
      - run: npm install
      - run: npm run build --if-present
      - run: npm install --no-save c8@10.1.2
      - run: npx c8 npm test
