name: Run JS tests
on:
  - push
  - pull_request
jobs:
  test-js:
    name: 'jsbt v0.4.1'
    uses: paulmillr/jsbt/.github/workflows/test-js.yml@2318b9efe24831b4bd4cadf720c96f071c69c64d
    # with:
    #   submodules: false
