name: Run tests
on:
  - push
  - pull_request
jobs:
  test-js:
    name: 'jsbt v0.4.0-pre' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/test-js.yml@fb1b826bd8f609dacb350852b4bc5038b9b86231
