name: Run JS tests with polyfill
on:
  - push
  - pull_request
jobs:
  node_polyfill:
    name: Node v${{ matrix.node }}
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        node: [18.20.5, 20.18.1, 22.13.0, 24.x] # LTS on Jan 2025. Hardcoded is more secure
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4
        with:
          registry-url: "https://registry.npmjs.org"
          cache: npm
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test:webcrypto
